language: node_js
sudo: false
node_js:
  - 8
script:
  - npm i
  - npm run lint
  - npm run test
  - npm run report-coverage
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
